"""
pipeline.py
-----------
Orchestrates the full AI film pipeline.

Keyframe model (N+1 boundary frames for N segments)
────────────────────────────────────────────────────
For 10 segments we generate 11 boundary keyframes:

  kf_0  ──[segment 0]── kf_1 ──[segment 1]── kf_2 ── … ── kf_10

  kf_0   = unique opening frame of the film
  kf_i   = shared boundary: last frame of segment i-1
                           = first frame of segment i
  kf_10  = unique closing frame of the film

This means only kf_0 and kf_10 are generated from dedicated descriptions.
Every interior keyframe (kf_1 … kf_9) is described as a narrative transition
point that must visually make sense as both an exit and an entry.

All keyframe images are generated with the chosen character reference image
as an IP-Adapter conditioning input to FLUX, keeping characters consistent
across the full film.

Video generation
────────────────
Each segment's video is generated by LTX-Video on Modal, receiving:
  - first_frame = chosen variant of kf_i
  - last_frame  = chosen variant of kf_{i+1}
  - prompt      = segment narration + action
All 10 videos are dispatched concurrently; Modal auto-scales containers.
"""

import asyncio
import base64
import json
import os
import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

import anthropic
import httpx

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
ANTHROPIC_API_KEY = os.environ["ANTHROPIC_API_KEY"]
# Both endpoints are printed after `modal deploy modal_app.py`
MODAL_IMAGE_ENDPOINT = os.environ.get(
    "MODAL_IMAGE_ENDPOINT",
    "https://<workspace>--ai-film-pipeline-image-endpoint.modal.run",
)
MODAL_VIDEO_ENDPOINT = os.environ.get(
    "MODAL_VIDEO_ENDPOINT",
    "https://<workspace>--ai-film-pipeline-video-endpoint.modal.run",
)

anthropic_client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

NUM_SEGMENTS  = 10
NUM_KEYFRAMES = NUM_SEGMENTS + 1   # 11


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------
@dataclass
class ScriptFragment:
    fragment_id: int
    title: str
    narration: str
    action: str
    dialogue: str
    characters_present: list[str]
    environment: str
    duration_seconds: int = 8


@dataclass
class KeyframeDescription:
    """Single boundary keyframe between two segments."""
    keyframe_id: int       # 0 … 10
    role: str              # "opening" | "transition" | "closing"
    prompt: str            # detailed FLUX image-gen prompt


@dataclass
class GeneratedImages:
    """Three image variants (base64 PNG) for a single prompt."""
    prompt: str
    variants: list[str]      # base64 PNGs
    chosen_index: int = 0    # set by the user in the UI


@dataclass
class PipelineState:
    idea: str = ""
    fragments: list[ScriptFragment] = field(default_factory=list)
    character_names: list[str] = field(default_factory=list)
    environment_name: str = ""

    # Step 2 – reference images
    character_refs: dict[str, GeneratedImages] = field(default_factory=dict)
    environment_ref: GeneratedImages | None = None

    # Step 3 – 11 boundary keyframe descriptions
    keyframe_descriptions: list[KeyframeDescription] = field(default_factory=list)

    # Step 4 – 11 keyframe images keyed "kf_0" … "kf_10" (3 variants each)
    keyframe_images: dict[str, GeneratedImages] = field(default_factory=dict)

    # Step 5 – video clips keyed by fragment_id (0-9)
    video_clips: dict[int, bytes] = field(default_factory=dict)

    final_film_path: str = ""


# ---------------------------------------------------------------------------
# Step 1 – Script generation
# ---------------------------------------------------------------------------
SCRIPT_SYSTEM = """\
You are a professional short-film screenwriter.
Given a film idea, produce a tight 1-to-2-minute script divided into
EXACTLY 10 fragments of ~8 seconds each.

Respond ONLY with a JSON array (no markdown fences, no preamble) where each
element has these keys:
  fragment_id          (integer 0-9)
  title                (short scene label)
  narration            (voiceover / descriptive narration, 1-2 sentences)
  action               (what physically happens on screen)
  dialogue             (spoken lines, or "" if none)
  characters_present   (array of character name strings)
  environment          (brief location description)
  duration_seconds     (always 8)

Keep characters consistent across all fragments (same names and descriptions).
"""


def generate_script(idea: str) -> list[ScriptFragment]:
    response = anthropic_client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=4096,
        system=SCRIPT_SYSTEM,
        messages=[{"role": "user", "content": idea}],
    )
    data: list[dict] = json.loads(response.content[0].text.strip())
    return [ScriptFragment(**d) for d in data]


# ---------------------------------------------------------------------------
# Step 3 – Keyframe description generation (N+1 boundary frames)
# ---------------------------------------------------------------------------
KEYFRAME_SYSTEM = """\
You are a cinematographer and storyboard artist working on a short film.

The film is divided into 10 consecutive 8-second segments. You must produce
EXACTLY 11 boundary-keyframe descriptions — one for each temporal boundary
between segments (plus the opening and closing frames).

Keyframe roles:
  kf_0    "opening"    : The very first frame of the film.
  kf_1-9  "transition" : The shared boundary between two consecutive segments.
                         This frame must make visual sense as BOTH the last
                         frame of segment i-1 AND the first frame of segment i.
  kf_10   "closing"    : The very last frame of the film.

For each keyframe write a detailed FLUX image-generation prompt that includes:
  - Camera angle and framing (wide shot, close-up, etc.)
  - Character positions, expressions, and poses (use the given character names)
  - Environment details, lighting, time of day
  - Color palette and emotional mood
  - Key props or visual elements

Respond ONLY with a JSON array of exactly 11 objects (no fences, no preamble):
  keyframe_id   (integer 0-10)
  role          ("opening" | "transition" | "closing")
  prompt        (detailed image-gen string)
"""


def generate_keyframe_descriptions(
    fragments: list[ScriptFragment],
    character_summary: str,
    environment_summary: str,
) -> list[KeyframeDescription]:
    script_summary = "\n".join(
        f"Segment {f.fragment_id} — {f.title}: {f.action}. {f.narration}"
        for f in fragments
    )
    user_msg = (
        f"Film script (10 segments):\n{script_summary}\n\n"
        f"Characters: {character_summary}\n"
        f"Main environment: {environment_summary}\n\n"
        f"Generate the 11 boundary keyframe descriptions."
    )
    resp = anthropic_client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=4096,
        system=KEYFRAME_SYSTEM,
        messages=[{"role": "user", "content": user_msg}],
    )
    data: list[dict] = json.loads(resp.content[0].text.strip())
    return [KeyframeDescription(**d) for d in data]


# ---------------------------------------------------------------------------
# Step 2 & 4 – Image generation via Modal FLUX endpoint
# ---------------------------------------------------------------------------
async def _call_image_endpoint(
    prompt: str,
    character_ref_b64: str | None = None,
    seeds: list[int] = (42, 1337, 99999),
    width: int = 1024,
    height: int = 576,
) -> GeneratedImages:
    async with httpx.AsyncClient(timeout=360, follow_redirects=True) as client:
        resp = await client.post(
            MODAL_IMAGE_ENDPOINT,
            json={
                "prompt": prompt,
                "seeds": list(seeds),
                "width": width,
                "height": height,
                "character_ref_b64": character_ref_b64,
            },
        )
        resp.raise_for_status()
        data = resp.json()
    return GeneratedImages(prompt=prompt, variants=data["images"])


def _chosen_char_b64(state: PipelineState) -> str | None:
    """Return the first chosen character reference as base64, if available."""
    if not state.character_refs:
        return None
    ref = next(iter(state.character_refs.values()))
    return ref.variants[ref.chosen_index]


async def generate_all_refs(state: PipelineState) -> None:
    """Concurrently generate character and environment reference images."""
    tasks = {}

    for char in state.character_names:
        prompt = (
            f"Character reference sheet for '{char}', full body portrait, "
            f"cinematic lighting, ultra-detailed, neutral background, concept art style"
        )
        tasks[f"char:{char}"] = _call_image_endpoint(prompt)

    env_prompt = (
        f"Environment concept art: {state.environment_name}, "
        f"cinematic wide establishing shot, dramatic lighting, ultra-detailed, film still"
    )
    tasks["env"] = _call_image_endpoint(env_prompt)

    results = await asyncio.gather(*tasks.values())
    for key, result in zip(tasks.keys(), results):
        if key.startswith("char:"):
            state.character_refs[key[5:]] = result
        else:
            state.environment_ref = result


async def generate_all_keyframe_images(state: PipelineState) -> None:
    """
    Concurrently generate 3 variants for each of the 11 boundary keyframes.
    Passes the chosen character reference to FLUX as IP-Adapter conditioning
    so all keyframes share the same character appearance.
    """
    char_b64 = _chosen_char_b64(state)
    style_suffix = "Cinematic film still, 16:9, photorealistic, 8K, no watermarks, no text"

    tasks = {
        f"kf_{kf.keyframe_id}": _call_image_endpoint(
            prompt=f"{kf.prompt}. {style_suffix}",
            character_ref_b64=char_b64,
        )
        for kf in state.keyframe_descriptions
    }

    results = await asyncio.gather(*tasks.values())
    for key, result in zip(tasks.keys(), results):
        state.keyframe_images[key] = result


# ---------------------------------------------------------------------------
# Step 5 – Video generation via Modal LTX-Video endpoint (all parallel)
# ---------------------------------------------------------------------------
async def _generate_one_clip(
    fragment: ScriptFragment,
    first_frame_b64: str,
    last_frame_b64: str,
) -> tuple[int, bytes]:
    """
    Call Modal LTX-Video for one segment.
    first_frame = chosen kf_{i}   last_frame = chosen kf_{i+1}
    """
    prompt = f"{fragment.narration} {fragment.action}".strip()
    async with httpx.AsyncClient(timeout=600, follow_redirects=True) as client:
        resp = await client.post(
            MODAL_VIDEO_ENDPOINT,
            json={
                "first_frame_b64": first_frame_b64,
                "last_frame_b64":  last_frame_b64,
                "prompt":          prompt,
                "fragment_id":     fragment.fragment_id,
                "seed":            42 + fragment.fragment_id,
            },
        )
        resp.raise_for_status()
        data = resp.json()

    return fragment.fragment_id, base64.b64decode(data["video_b64"])


async def generate_all_video_clips(state: PipelineState) -> None:
    """
    Fire all 10 video jobs concurrently.

    Segment i  →  kf_{i} (first) to kf_{i+1} (last)

    Modal's concurrency_limit=10 on LTXVideoGenerator means the platform
    spins up to 10 parallel GPU containers to service all requests at once.
    """
    def chosen_b64(key: str) -> str:
        gi = state.keyframe_images[key]
        return gi.variants[gi.chosen_index]

    tasks = [
        _generate_one_clip(
            fragment=frag,
            first_frame_b64=chosen_b64(f"kf_{frag.fragment_id}"),
            last_frame_b64=chosen_b64(f"kf_{frag.fragment_id + 1}"),
        )
        for frag in state.fragments
    ]

    results = await asyncio.gather(*tasks)
    state.video_clips = {fid: clip for fid, clip in results}


# ---------------------------------------------------------------------------
# Step 6 – Assemble with ffmpeg
# ---------------------------------------------------------------------------
def assemble_film(state: PipelineState, output_path: str = "final_film.mp4") -> str:
    with tempfile.TemporaryDirectory() as tmp:
        clip_paths = []
        for i in range(NUM_SEGMENTS):
            p = os.path.join(tmp, f"clip_{i:02d}.mp4")
            Path(p).write_bytes(state.video_clips[i])
            clip_paths.append(p)

        list_file = os.path.join(tmp, "clips.txt")
        with open(list_file, "w") as f:
            for cp in clip_paths:
                f.write(f"file '{cp}'\n")

        subprocess.run(
            ["ffmpeg", "-y", "-f", "concat", "-safe", "0",
             "-i", list_file, "-c", "copy", output_path],
            check=True,
        )

    state.final_film_path = output_path
    return output_path


# ---------------------------------------------------------------------------
# Public API used by server.py
# ---------------------------------------------------------------------------
async def run_pipeline(idea: str, on_progress=None) -> PipelineState:
    """Steps 1-4. Pauses after keyframe images so user can select variants."""
    state = PipelineState(idea=idea)

    async def emit(step, data=None):
        if on_progress:
            await on_progress(step, data)

    await emit("script:start")
    state.fragments = generate_script(idea)
    state.character_names = list({c for f in state.fragments for c in f.characters_present})
    state.environment_name = state.fragments[0].environment
    await emit("script:done", [f.__dict__ for f in state.fragments])

    await emit("refs:start")
    await generate_all_refs(state)
    await emit("refs:done")
    # ← user selects character ref here; server.py saves choice before step 3

    await emit("keyframes:start")
    state.keyframe_descriptions = generate_keyframe_descriptions(
        state.fragments,
        character_summary=", ".join(state.character_names),
        environment_summary=state.environment_name,
    )
    await emit("keyframes:done", [kf.__dict__ for kf in state.keyframe_descriptions])

    await emit("keyframe_images:start")
    await generate_all_keyframe_images(state)   # uses chosen char ref
    await emit("keyframe_images:done")
    # ← user selects keyframe variants; then POST /continue

    return state


async def continue_pipeline(state: PipelineState, on_progress=None) -> PipelineState:
    """Steps 5-6: parallel video generation + ffmpeg assembly."""
    async def emit(step, data=None):
        if on_progress:
            await on_progress(step, data)

    await emit("video:start")
    await generate_all_video_clips(state)
    await emit("video:done")

    await emit("assembly:start")
    assemble_film(state)
    await emit("assembly:done", {"path": state.final_film_path})

    return state